# Generated by Django 4.2.11 on 2024-04-04 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petadoptapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name',
        ),
    ]
